# Generated by Django 3.2.25 on 2026-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_phone_number_user_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.TextField(blank=True, default='{"outreach": true, "announcements": true, "reminders": true}'),
        ),
    ]
