# Generated by Django 6.0.6 on 2026-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('participant', 'Participant')], default='participant', max_length=50),
        ),
    ]
