# Generated by Django 6.0.6 on 2026-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20260715_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
