# Generated by Django 6.0.5 on 2026-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration open', 'Registration Open'), ('registration closed', 'Registration Closed'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('hidden', 'Hidden')], default='draft', max_length=50),
        ),
    ]
