# Generated by Django 6.0.6 on 2026-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('bootcamp', 'Bootcamp'), ('introduction', 'Introduction'), ('speaker_session', 'Speaker Session'), ('hackathon', 'Hackathon'), ('other', 'Other')], default='workshop', max_length=50),
        ),
    ]
