# Generated by Django 3.2.25 on 2026-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_announcement_session_surveyquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='gdg-workspace', max_length=100, unique=True)),
                ('name', models.CharField(default='GDG Workspace', max_length=255)),
                ('location', models.CharField(blank=True, default='Coimbatore, Tamil Nadu, India', max_length=255)),
                ('description', models.TextField(blank=True, default='Kumaraguru Google Developer Group Chapter.')),
                ('logo', models.URLField(blank=True, default='https://www.gstatic.com/devrel-devsite/prod/v559d28dbd68e4de88d1d8ef35b54203a7a97c27632669e46a782e46e8557ee7a/developers/images/touchicon-180.png', max_length=500)),
                ('banner', models.URLField(blank=True, default='https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80', max_length=500)),
                ('theme_color', models.CharField(default='#1A73E8', max_length=50)),
                ('ga_tracking_id', models.CharField(default='G-XXXXXXXXXX', max_length=50)),
            ],
        ),
    ]
