# Generated by Django 6.0.6 on 2026-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20260629_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersetting',
            name='description',
            field=models.TextField(blank=True, default='Kumaraguru Research and Exploration (RÉ) Chapter.'),
        ),
        migrations.AlterField(
            model_name='chaptersetting',
            name='name',
            field=models.CharField(default='Research and Exploration (RÉ) Workspace', max_length=255),
        ),
        migrations.AlterField(
            model_name='chaptersetting',
            name='theme_color',
            field=models.CharField(default='#1b2b4b', max_length=50),
        ),
    ]
