# Generated by Django 3.2.25 on 2026-07-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20260715_1919'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_max_team_size_event_min_team_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='authentication.adminprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
