# Generated by Django 3.2.25 on 2026-07-16 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20260715_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='domain_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rig_vertical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration open', 'Registration Open'), ('registration closed', 'Registration Closed'), ('completed', 'Completed'), ('report_in_progress', 'Report In Progress'), ('report_completed', 'Report Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('hidden', 'Hidden')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('docx_file', models.FileField(upload_to='generated_reports/docx/')),
                ('pdf_file', models.FileField(upload_to='generated_reports/pdf/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_versions', to='events.event')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Rich text field containing the event summary.')),
                ('outcomes', models.TextField(blank=True, help_text='Rich text field containing outcomes & key takeaways.')),
                ('sponsored_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_utilized', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_returned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prize_position', models.CharField(blank=True, help_text='e.g. 1st, 2nd, 3rd', max_length=255, null=True)),
                ('prize_details', models.TextField(blank=True, help_text='Details of winners and prize items.', null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='events.event')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_assets/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('photo', 'Event Photograph'), ('invitation_poster', 'Invitation / Poster'), ('certificate', 'Certificates / Achievement'), ('media_proof', 'Newspaper / Social Media Proof'), ('attendance_list', 'Attendance / Participation List'), ('budget_proof', 'Budget / Expense Proof'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='events.event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
