# Generated by Django 6.0.6 on 2026-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20260716_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='docx_file',
            field=models.FileField(upload_to='generated_reports/docx/'),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='pdf_file',
            field=models.FileField(upload_to='generated_reports/pdf/'),
        ),
    ]
