# Generated by Django 6.0.6 on 2026-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_options_alter_reportversion_docx_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
    ]
