# Generated by Django 3.2.25 on 2026-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.TextField(blank=True, default='{}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
