# Generated by Django 3.2.25 on 2026-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='metadata',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
