# Generated by Django 3.2.25 on 2026-07-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20260701_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'verbose_name': 'Event Outreach', 'verbose_name_plural': 'Event Outreach'},
        ),
    ]
