# Generated by Django 3.2.25 on 2026-07-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20260715_1919'),
        ('communication', '0004_alter_emailcampaign_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to='authentication.adminprofile'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_campaigns_profile', to='authentication.adminprofile'),
        ),
    ]
